/**
 * Script generator: produces run.sh, setup.sh, and SKILL.md from WorkflowYAML.
 *
 * All generated scripts:
 * - Have proper shebang (#!/usr/bin/env bash)
 * - Use set -e for fail-fast
 * - Validate required tools via `command -v`
 * - Validate required environment variables
 */

import type { WorkflowYAML } from "./schema.js";

// ── run.sh ─────────────────────────────────────────────────────────────

/**
 * Generate the main orchestrator script (run.sh).
 */
export function generateRunScript(workflow: WorkflowYAML): string {
  const lines: string[] = [];

  lines.push("#!/usr/bin/env bash");
  lines.push("set -euo pipefail");
  lines.push("");
  lines.push(`# ${workflow.metadata.name} — orchestrator`);
  lines.push(`# ${workflow.metadata.description}`);
  lines.push(`# Generated by agents-cli compose`);
  lines.push("");

  // Source environment
  lines.push("SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"");
  lines.push("");

  // Load .env if present
  lines.push("if [ -f \"$SCRIPT_DIR/.env\" ]; then");
  lines.push("  set -a && source \"$SCRIPT_DIR/.env\" && set +a");
  lines.push("fi");
  lines.push("");

  // Validate required env vars
  if (workflow.spec.env.length > 0) {
    lines.push("# Validate required environment variables");
    for (const env of workflow.spec.env) {
      if (env.required) {
        lines.push(`if [ -z "\${${env.name}:-}" ]; then`);
        lines.push(`  echo "ERROR: ${env.name} is required — ${env.description}" >&2`);
        lines.push("  exit 1");
        lines.push("fi");
      }
    }
    lines.push("");
  }

  // Execute steps
  for (let i = 0; i < workflow.spec.steps.length; i++) {
    const step = workflow.spec.steps[i]!;

    lines.push(`# Step ${i + 1}: ${step.name}`);
    lines.push(`echo ">>> [${i + 1}/${workflow.spec.steps.length}] ${step.name}"`);

    // Conditional execution
    if (step.condition) {
      lines.push(`if ${step.condition}; then`);
    }

    // Build command
    const args = step.args.length > 0 ? ` ${step.args.join(" ")}` : "";
    const cmd = `${step.command}${args}`;

    // Error handling
    switch (step.onFailure) {
      case "skip":
        lines.push(`${cmd} || echo "WARN: Step '${step.name}' failed, skipping"`);
        break;
      case "retry":
        lines.push(`for _attempt in 1 2 ${step.retries ?? 3}; do`);
        lines.push(`  ${cmd} && break`);
        lines.push(`  echo "WARN: Step '${step.name}' failed (attempt $_attempt), retrying..."`);
        lines.push(`  sleep ${parseRetryDelay(workflow.spec.errorHandling.retryDelay)}`);
        lines.push("done");
        break;
      default: // "stop"
        lines.push(cmd);
        break;
    }

    if (step.condition) {
      lines.push("fi");
    }

    lines.push("");
  }

  lines.push(`echo ">>> Workflow '${workflow.metadata.name}' completed successfully"`);
  lines.push("");

  return lines.join("\n");
}

// ── setup.sh ───────────────────────────────────────────────────────────

/**
 * Generate the setup/validation script (setup.sh).
 */
export function generateSetupScript(workflow: WorkflowYAML): string {
  const lines: string[] = [];

  lines.push("#!/usr/bin/env bash");
  lines.push("set -e");
  lines.push("");
  lines.push(`# ${workflow.metadata.name} — setup & validation`);
  lines.push(`# Validates that all required tools and env vars are present`);
  lines.push("");

  // Collect unique tools from step commands
  const tools = new Set<string>();
  for (const step of workflow.spec.steps) {
    const bin = step.command.split(/\s+/)[0];
    if (bin) tools.add(bin);
  }

  // Check tools
  if (tools.size > 0) {
    lines.push("# Check required tools");
    lines.push("MISSING=0");
    for (const tool of tools) {
      lines.push(`if ! command -v ${tool} &>/dev/null; then`);
      lines.push(`  echo "MISSING: ${tool}" >&2`);
      lines.push("  MISSING=$((MISSING + 1))");
      lines.push("fi");
    }
    lines.push("");
    lines.push("if [ \"$MISSING\" -gt 0 ]; then");
    lines.push("  echo \"ERROR: $MISSING required tool(s) not found\" >&2");
    lines.push("  exit 1");
    lines.push("fi");
    lines.push("echo \"All ${tools.size} required tools found\"");
    lines.push("");
  }

  // Check env vars
  const requiredEnv = workflow.spec.env.filter((e) => e.required);
  if (requiredEnv.length > 0) {
    lines.push("# Check required environment variables");
    lines.push("ENV_MISSING=0");
    for (const env of requiredEnv) {
      lines.push(`if [ -z "\${${env.name}:-}" ]; then`);
      lines.push(`  echo "MISSING: ${env.name} — ${env.description}" >&2`);
      lines.push("  ENV_MISSING=$((ENV_MISSING + 1))");
      lines.push("fi");
    }
    lines.push("");
    lines.push("if [ \"$ENV_MISSING\" -gt 0 ]; then");
    lines.push("  echo \"ERROR: $ENV_MISSING required env var(s) not set\" >&2");
    lines.push("  exit 1");
    lines.push("fi");
    lines.push(`echo "All ${requiredEnv.length} required env vars set"`);
    lines.push("");
  }

  lines.push("echo \"Setup validation passed\"");
  lines.push("");

  return lines.join("\n");
}

// ── SKILL.md ───────────────────────────────────────────────────────────

/**
 * Generate SKILL.md from a WorkflowYAML.
 */
export function generateSkillMdFromWorkflow(workflow: WorkflowYAML): string {
  const lines: string[] = [];

  // Frontmatter
  lines.push("---");
  lines.push(`name: ${workflow.metadata.name}`);
  lines.push(`description: ${workflow.metadata.description}`);
  lines.push(`version: ${workflow.metadata.version}`);
  lines.push(`domain: ${workflow.metadata.domain}`);
  if (workflow.metadata.tags.length > 0) {
    lines.push(`tags: ${workflow.metadata.tags.join(", ")}`);
  }
  lines.push("---");
  lines.push("");

  // Description with trigger phrases
  const skills = workflow.spec.steps.map((s) => s.skill);
  lines.push(`Use when orchestrating ${workflow.metadata.domain} workflows, `);
  lines.push(`composing ${skills.join(", ")} into automated pipelines, `);
  lines.push(`running ${workflow.metadata.name} sequences. `);
  lines.push(`Do NOT use for individual tool invocation or unrelated domains.`);
  lines.push("");

  // Pipeline overview
  lines.push("## Pipeline");
  lines.push("");
  const stepNames = workflow.spec.steps.map((s) => s.name);
  lines.push(stepNames.join(" → "));
  lines.push("");

  // Steps table
  lines.push("## Steps");
  lines.push("");
  lines.push("| # | Step | Command | On Failure |");
  lines.push("|---|------|---------|------------|");
  for (let i = 0; i < workflow.spec.steps.length; i++) {
    const step = workflow.spec.steps[i]!;
    lines.push(`| ${i + 1} | ${step.name} | \`${step.command}\` | ${step.onFailure} |`);
  }
  lines.push("");

  // Environment variables
  if (workflow.spec.env.length > 0) {
    lines.push("## Environment Variables");
    lines.push("");
    lines.push("| Variable | Required | Description |");
    lines.push("|----------|----------|-------------|");
    for (const env of workflow.spec.env) {
      lines.push(`| \`${env.name}\` | ${env.required ? "yes" : "no"} | ${env.description} |`);
    }
    lines.push("");
  }

  // Data flow
  if (workflow.spec.dataFlow.length > 0) {
    lines.push("## Data Flow");
    lines.push("");
    for (const edge of workflow.spec.dataFlow) {
      lines.push(`- \`${edge.from}\` → \`${edge.to}\` (${edge.type})`);
    }
    lines.push("");
  }

  // Usage
  lines.push("## Usage");
  lines.push("");
  lines.push("```bash");
  lines.push("# Setup");
  lines.push("bash scripts/setup.sh");
  lines.push("");
  lines.push("# Run");
  lines.push("bash scripts/run.sh");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

// ── Helpers ────────────────────────────────────────────────────────────

function parseRetryDelay(delay: string): number {
  const match = delay.match(/^(\d+)(s|m|ms)?$/);
  if (!match) return 5;
  const value = parseInt(match[1]!, 10);
  switch (match[2]) {
    case "m": return value * 60;
    case "ms": return Math.ceil(value / 1000);
    default: return value;
  }
}
