// Assistant template - personal AI assistant for repo processing

import type { WorkflowTemplate, AssistantConfig } from "./types.js";

export const ASSISTANT_TEMPLATE: WorkflowTemplate<AssistantConfig> = {
  name: "assistant",
  description: "Personal AI assistant for repo processing and indexing",
  strategy: "event-driven-pipeline",

  generateAgent: (config: AssistantConfig) => {
    const triggers = config.triggers || ["cli"];
    const steps = config.steps || [
      { name: "fetch", action: "npx opensrc fetch" },
      { name: "index", action: "npx agents-cli index" },
      { name: "embed", action: "npx agents-cli embed" },
      { name: "skill", action: "npx agents-cli skill" },
    ];

    return `/**
 * ${config.name || "AI Assistant"} - Personal repo processing assistant
 * Generated by agents-cli
 */

import { AssistantPipeline, Trigger, PipelineStep } from '@opensrc/workflow';

interface ProcessResult {
  repoUrl: string;
  status: 'success' | 'failed' | 'partial';
  steps: StepResult[];
  skillPath?: string;
  duration: number;
}

interface StepResult {
  name: string;
  success: boolean;
  output?: string;
  error?: string;
  duration: number;
}

// Pipeline steps configuration
const steps: PipelineStep[] = [
${steps.map(s => `  { name: '${s.name}', action: '${s.action}' },`).join("\n")}
];

// Create pipeline
const pipeline = new AssistantPipeline({
  triggers: [
${triggers.map(t => `    { type: '${t}'${t === "webhook" ? ", path: '/process'" : ""}${t === "cli" ? ", command: 'process-repo'" : ""} },`).join("\n")}
  ],
  steps,
  notify: { email: process.env.NOTIFY_EMAIL },
  retryAttempts: 3,
});

/**
 * Process a repository URL through the pipeline
 */
export async function processRepo(repoUrl: string): Promise<ProcessResult> {
  const startTime = Date.now();
  const stepResults: StepResult[] = [];

  console.log(\`Processing repository: \${repoUrl}\`);

  for (const step of steps) {
    const stepStart = Date.now();
    try {
      const output = await executeStep(step, repoUrl);
      stepResults.push({
        name: step.name,
        success: true,
        output,
        duration: Date.now() - stepStart,
      });
    } catch (error) {
      stepResults.push({
        name: step.name,
        success: false,
        error: (error as Error).message,
        duration: Date.now() - stepStart,
      });

      // Continue with remaining steps or fail?
      // For now, continue
    }
  }

  const successCount = stepResults.filter(r => r.success).length;
  const status = successCount === steps.length
    ? 'success'
    : successCount > 0
      ? 'partial'
      : 'failed';

  const result: ProcessResult = {
    repoUrl,
    status,
    steps: stepResults,
    skillPath: status !== 'failed' ? \`.claude/skills/\${extractRepoName(repoUrl)}/SKILL.md\` : undefined,
    duration: Date.now() - startTime,
  };

  // Send notification if configured
  if (process.env.NOTIFY_EMAIL) {
    await sendNotification(result);
  }

  return result;
}

/**
 * Execute a single pipeline step
 */
async function executeStep(step: PipelineStep, repoUrl: string): Promise<string> {
  const { execSync } = require('child_process');

  const command = step.action.replace('{repo}', repoUrl);
  const output = execSync(command, {
    encoding: 'utf-8',
    timeout: 300000, // 5 minutes
    maxBuffer: 10 * 1024 * 1024, // 10MB
  });

  return output;
}

/**
 * Extract repository name from URL
 */
function extractRepoName(repoUrl: string): string {
  const match = repoUrl.match(/github\\.com[\\/]([^\\/]+\\/[^\\/]+)/);
  return match ? match[1].replace('/', '-').replace('.git', '') : 'unknown';
}

/**
 * Send notification email
 */
async function sendNotification(result: ProcessResult): Promise<void> {
  // Placeholder for email notification
  console.log(\`Sending notification for \${result.repoUrl}: \${result.status}\`);
}

${triggers.includes("webhook") ? `
/**
 * Webhook handler (for use with Express, Hono, etc.)
 */
export async function handleWebhook(req: Request): Promise<Response> {
  const { repoUrl } = await req.json();

  if (!repoUrl) {
    return new Response(JSON.stringify({ error: 'repoUrl required' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // Process asynchronously
  processRepo(repoUrl).catch(console.error);

  return new Response(JSON.stringify({
    message: 'Processing started',
    repoUrl,
  }), {
    status: 202,
    headers: { 'Content-Type': 'application/json' },
  });
}
` : ""}

${triggers.includes("schedule") ? `
/**
 * Schedule processor - runs on a schedule
 */
export function startScheduler(intervalMs: number = 3600000): NodeJS.Timeout {
  return setInterval(async () => {
    // Get pending repos from queue
    const pendingRepos = await getPendingRepos();

    for (const repo of pendingRepos) {
      try {
        await processRepo(repo.url);
      } catch (error) {
        console.error(\`Failed to process \${repo.url}:\`, error);
      }
    }
  }, intervalMs);
}

async function getPendingRepos(): Promise<Array<{ url: string }>> {
  // Placeholder - implement based on your queue system
  return [];
}
` : ""}

// CLI entry point
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  const repoUrl = process.argv[2];

  if (!repoUrl) {
    console.error('Usage: node assistant-agent.ts <repo-url>');
    process.exit(1);
  }

  processRepo(repoUrl)
    .then(result => console.log(JSON.stringify(result, null, 2)))
    .catch(err => {
      console.error('Error:', err.message);
      process.exit(1);
    });
}
`;
  },

  generateEnv: (config: AssistantConfig) => {
    const envVars: string[] = [];

    if (config.notify?.email) {
      envVars.push("NOTIFY_EMAIL=your_email@example.com");
      envVars.push("RESEND_API_KEY=your_resend_api_key");
    }

    envVars.push("OPENAI_API_KEY=your_openai_key");

    return envVars;
  },
};
