// Council template - multi-provider consensus workflow

import type { WorkflowTemplate, CouncilConfig } from "./types.js";

export const COUNCIL_TEMPLATE: WorkflowTemplate<CouncilConfig> = {
  name: "council",
  description: "Multi-provider consensus workflow for APIs like image generation, LLM routing",
  strategy: "parallel-with-consensus",

  generateAgent: (config: CouncilConfig) => {
    const providers = config.providers || [];

    return `/**
 * ${config.name || "Council Workflow"} - Multi-provider consensus
 * Generated by pop-skills
 */

import { CouncilVoter, ProviderClient } from '@opensrc/workflow';

interface CouncilResult {
  provider: string;
  result: unknown;
  score: number;
  latency: number;
}

interface ConsensusOutput {
  consensus: unknown;
  votes: CouncilResult[];
  winner: string;
  confidence: number;
}

const providers: ProviderClient[] = [
${providers.map(p => `  {
    name: '${p.name}',
    client: new ${p.clientClass}(process.env.${p.envKey}),
  },`).join("\n")}
];

const council = new CouncilVoter({
  providers,
  strategy: '${config.strategy || "parallel-with-consensus"}',
  votingMethod: '${config.votingMethod || "quality-score"}',
  fallback: ${config.fallback !== false},
  timeout: 30000,
});

/**
 * Execute the council workflow
 */
export async function execute(prompt: string): Promise<ConsensusOutput> {
  const startTime = Date.now();

  try {
    const results = await council.execute({ prompt });

    return {
      consensus: results.consensus,
      votes: results.votes.map((v: any) => ({
        provider: v.provider,
        result: v.result,
        score: v.score,
        latency: v.latency,
      })),
      winner: results.winner,
      confidence: results.confidence,
    };
  } catch (error) {
    console.error('Council execution failed:', error);
    throw error;
  }
}

/**
 * Execute with fallback to single provider
 */
export async function executeWithFallback(
  prompt: string,
  fallbackProvider: string = '${providers[0]?.name || "default"}'
): Promise<unknown> {
  try {
    const result = await execute(prompt);
    return result.consensus;
  } catch {
    // Fallback to single provider
    const provider = providers.find(p => p.name === fallbackProvider);
    if (provider) {
      return provider.client.generate(prompt);
    }
    throw new Error(\`Fallback provider \${fallbackProvider} not found\`);
  }
}

// CLI entry point
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  const prompt = process.argv[2] || 'Generate an image of a sunset';
  execute(prompt)
    .then(result => console.log(JSON.stringify(result, null, 2)))
    .catch(err => {
      console.error('Error:', err.message);
      process.exit(1);
    });
}
`;
  },

  generateEnv: (config: CouncilConfig) => {
    return (config.providers || []).map(p => `${p.envKey}=your_${p.name.toLowerCase()}_api_key`);
  },
};
