// E-commerce template - full-stack merchandising with payments

import type { WorkflowTemplate, EcommerceConfig } from "./types.js";

export const ECOMMERCE_TEMPLATE: WorkflowTemplate<EcommerceConfig> = {
  name: "ecommerce",
  description: "Full-stack e-commerce with payments and smooth checkout",
  strategy: "layered-architecture",

  generateAgent: (config: EcommerceConfig) => {
    return `/**
 * ${config.name || "E-commerce Store"} - Full-stack merchandising
 * Generated by pop-skills
 */

// Framework imports based on tech stack
${config.frontend?.includes("next") ? "import { NextApiRequest, NextApiResponse } from 'next';" : ""}
${config.backend?.includes("hono") ? "import { Hono } from 'hono';" : ""}
${config.backend?.includes("trpc") ? "import { initTRPC } from '@trpc/server';" : ""}
${config.payments?.includes("stripe") ? "import Stripe from 'stripe';" : ""}
${config.database?.includes("drizzle") ? "import { drizzle } from 'drizzle-orm/better-sqlite3';" : ""}

// Types
interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  currency: string;
  images: string[];
  inventory: number;
}

interface CartItem {
  product: Product;
  quantity: number;
}

interface Cart {
  items: CartItem[];
  total: number;
  currency: string;
}

interface CheckoutSession {
  id: string;
  url: string;
  cart: Cart;
}

interface Order {
  id: string;
  items: CartItem[];
  total: number;
  status: 'pending' | 'paid' | 'shipped' | 'delivered';
  createdAt: Date;
}

// Stripe client
${config.payments?.includes("stripe") ? `
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2023-10-16',
});
` : "// Payment provider not configured"}

// Database setup
${config.database?.includes("drizzle") ? `
import Database from 'better-sqlite3';
const sqlite = new Database('store.db');
const db = drizzle(sqlite);
` : "// Database not configured"}

/**
 * Cart operations
 */
export const cartService = {
  async getCart(userId: string): Promise<Cart> {
    // Implementation
    return { items: [], total: 0, currency: 'USD' };
  },

  async addItem(userId: string, productId: string, quantity: number): Promise<Cart> {
    // Implementation
    return this.getCart(userId);
  },

  async removeItem(userId: string, productId: string): Promise<Cart> {
    // Implementation
    return this.getCart(userId);
  },

  async updateQuantity(userId: string, productId: string, quantity: number): Promise<Cart> {
    // Implementation
    return this.getCart(userId);
  },

  async clearCart(userId: string): Promise<void> {
    // Implementation
  },
};

/**
 * Checkout operations
 */
export const checkoutService = {
  async createSession(cart: Cart): Promise<CheckoutSession> {
    ${config.payments?.includes("stripe") ? `
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: cart.items.map(item => ({
        price_data: {
          currency: cart.currency,
          product_data: {
            name: item.product.name,
          },
          unit_amount: item.product.price * 100,
        },
        quantity: item.quantity,
      })),
      mode: 'payment',
      success_url: process.env.SUCCESS_URL,
      cancel_url: process.env.CANCEL_URL,
    });

    return {
      id: session.id,
      url: session.url!,
      cart,
    };
    ` : 'throw new Error("Payment provider not configured");'}
  },

  async handleWebhook(payload: string, signature: string): Promise<Order> {
    ${config.payments?.includes("stripe") ? `
    const event = stripe.webhooks.constructEvent(
      payload,
      signature,
      process.env.STRIPE_WEBHOOK_SECRET!
    );

    if (event.type === 'checkout.session.completed') {
      const session = event.data.object;
      // Create order in database
      return {
        id: session.id,
        items: [],
        total: session.amount_total! / 100,
        status: 'paid',
        createdAt: new Date(),
      };
    }

    throw new Error('Unhandled event type');
    ` : 'throw new Error("Payment provider not configured");'}
  },
};

/**
 * Product operations
 */
export const productService = {
  async list(options?: { category?: string; limit?: number }): Promise<Product[]> {
    // Implementation
    return [];
  },

  async get(id: string): Promise<Product | null> {
    // Implementation
    return null;
  },

  async search(query: string): Promise<Product[]> {
    // Implementation
    return [];
  },
};

// API routes
${config.backend?.includes("hono") ? `
const app = new Hono();

app.get('/products', async (c) => {
  const products = await productService.list();
  return c.json(products);
});

app.get('/cart', async (c) => {
  const userId = c.req.header('x-user-id');
  const cart = await cartService.getCart(userId);
  return c.json(cart);
});

app.post('/cart/add', async (c) => {
  const userId = c.req.header('x-user-id');
  const { productId, quantity } = await c.req.json();
  const cart = await cartService.addItem(userId, productId, quantity);
  return c.json(cart);
});

app.post('/checkout', async (c) => {
  const userId = c.req.header('x-user-id');
  const cart = await cartService.getCart(userId);
  const session = await checkoutService.createSession(cart);
  return c.json(session);
});

export default app;
` : "// API routes not configured"}
`;
  },

  generateEnv: (config: EcommerceConfig) => {
    const envVars: string[] = [];

    if (config.payments?.includes("stripe")) {
      envVars.push("STRIPE_SECRET_KEY=your_stripe_secret_key");
      envVars.push("STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret");
      envVars.push("SUCCESS_URL=http://localhost:3000/success");
      envVars.push("CANCEL_URL=http://localhost:3000/cancel");
    }

    if (config.database?.includes("drizzle")) {
      envVars.push("DATABASE_URL=./store.db");
    }

    return envVars;
  },

  generateStructure: (_config: EcommerceConfig) => ({
    directories: [
      "src/frontend/components",
      "src/frontend/pages",
      "src/frontend/styles",
      "src/backend/api",
      "src/backend/services",
      "src/db/schema",
      "src/db/migrations",
      "public/images",
    ],
    files: [
      "src/frontend/pages/index.tsx",
      "src/frontend/pages/product/[id].tsx",
      "src/frontend/pages/cart.tsx",
      "src/frontend/pages/checkout.tsx",
      "src/frontend/components/ProductCard.tsx",
      "src/frontend/components/CartItem.tsx",
      "src/backend/api/products.ts",
      "src/backend/api/cart.ts",
      "src/backend/api/checkout.ts",
      "src/db/schema/products.ts",
      "src/db/schema/orders.ts",
      "src/db/schema/users.ts",
    ],
  }),
};
