// Publishing template - multi-platform social publishing

import type { WorkflowTemplate, PublishingConfig } from "./types.js";

export const PUBLISHING_TEMPLATE: WorkflowTemplate<PublishingConfig> = {
  name: "publishing",
  description: "Multi-platform social publishing with fan-out pattern",
  strategy: "fan-out-with-confirmation",

  generateAgent: (config: PublishingConfig) => {
    const platforms = config.platforms || [];

    return `/**
 * ${config.name || "Publishing Workflow"} - Multi-platform social publishing
 * Generated by agents-cli
 */

import { SocialPublisher, Platform } from '@opensrc/workflow';

interface Content {
  text: string;
  images?: string[];
  video?: string;
  link?: string;
  scheduledAt?: Date;
}

interface PublishResult {
  platform: string;
  success: boolean;
  postId?: string;
  url?: string;
  error?: string;
}

interface FanOutResult {
  results: PublishResult[];
  successful: number;
  failed: number;
  analytics?: Record<string, unknown>;
}

const platforms: Platform[] = [
${platforms.map(p => `  {
    name: '${p.name}',
    client: new ${p.clientClass}(process.env.${p.envKey}),
  },`).join("\n")}
];

const publisher = new SocialPublisher({
  platforms,
  retryAttempts: 3,
  retryDelay: 1000,
});

/**
 * Publish content to all configured platforms
 */
export async function publish(content: Content): Promise<FanOutResult> {
  const results: PublishResult[] = [];

  // Fan out to all platforms
  const promises = platforms.map(async (platform) => {
    try {
      const result = await publisher.publish(platform.name, content);
      return {
        platform: platform.name,
        success: true,
        postId: result.id,
        url: result.url,
      };
    } catch (error) {
      return {
        platform: platform.name,
        success: false,
        error: (error as Error).message,
      };
    }
  });

  const settled = await Promise.allSettled(promises);

  for (const result of settled) {
    if (result.status === 'fulfilled') {
      results.push(result.value);
    } else {
      results.push({
        platform: 'unknown',
        success: false,
        error: result.reason?.message || 'Unknown error',
      });
    }
  }

  const successful = results.filter(r => r.success).length;
  const failed = results.length - successful;

  return {
    results,
    successful,
    failed,
    analytics: ${config.collectAnalytics} ? await collectAnalytics(results) : undefined,
  };
}

/**
 * Publish to specific platforms only
 */
export async function publishTo(
  platformNames: string[],
  content: Content
): Promise<FanOutResult> {
  const filtered = platforms.filter(p => platformNames.includes(p.name));
  // ... similar to publish()
  return publish(content);
}

/**
 * Schedule content for future publishing
 */
export async function schedule(
  content: Content,
  scheduledAt: Date
): Promise<{ jobId: string; scheduledAt: Date }> {
  // Schedule the publish job
  const jobId = await publisher.schedule(content, scheduledAt);
  return { jobId, scheduledAt };
}

async function collectAnalytics(results: PublishResult[]): Promise<Record<string, unknown>> {
  // Placeholder for analytics collection
  return {
    totalPublished: results.filter(r => r.success).length,
    timestamp: new Date().toISOString(),
  };
}

// CLI entry point
if (import.meta.url === \`file://\${process.argv[1]}\`) {
  const text = process.argv[2] || 'Hello, world!';
  publish({ text })
    .then(result => console.log(JSON.stringify(result, null, 2)))
    .catch(err => {
      console.error('Error:', err.message);
      process.exit(1);
    });
}
`;
  },

  generateEnv: (config: PublishingConfig) => {
    return (config.platforms || []).map(p =>
      `${p.envKey}=your_${p.name.toLowerCase()}_api_key`
    );
  },
};
