/**
 * workflow-skill-gen.ts — Convert SkillWorkflow into SKILL.md + scripts.
 *
 * Each workflow becomes a skill directory:
 *   skills/<workflow-name>/
 *     SKILL.md            — Frontmatter with ingredients = component skills
 *     scripts/run.sh      — Chains CLI commands in order
 *     scripts/setup.sh    — Installs all dependencies
 *     references/workflow.md — Step diagram + conditions
 */

import type { SkillWorkflow } from "./workflow-composer.js";

// ── SKILL.md Generation ────────────────────────────────────────────────

/**
 * Generate SKILL.md content for a composed workflow.
 */
export function generateWorkflowSkillMd(workflow: SkillWorkflow): string {
  const ingredients = workflow.dependencies.map(d => d.replace(/^src-/, "")).join(", ");
  const triggerList = workflow.triggers.join(", ");
  const stepList = workflow.steps.map(s => `${s.name} (${s.skill})`).join(", ");

  const description = `Use when running ${workflow.name} workflow. ` +
    `Executes ${workflow.steps.length} steps: ${stepList}. ` +
    `Triggers: ${triggerList}. ` +
    `Do NOT use for single-tool operations that don't need orchestration.`;

  const stepDocs = workflow.steps.map((s, i) => {
    const failAction = s.onFailure === "stop" ? "abort pipeline" : s.onFailure === "retry" ? "retry once" : "continue";
    return `${i + 1}. **${s.name}** — \`${s.command}${s.args.length > 0 ? " " + s.args.join(" ") : ""}\`\n   - Skill: ${s.skill}\n   - On failure: ${failAction}${s.condition ? `\n   - Condition: ${s.condition}` : ""}`;
  }).join("\n");

  return `---
name: ${workflow.name}
description: "${description}"
version: 1.0.0
ingredients: ${ingredients}
tags: workflow, automation, ${workflow.triggers.join(", ")}
domain: workflow
allowed-tools: Bash, Read, Write
---

# ${workflow.name}

${workflow.description}

## Steps

${stepDocs}

## Quick Start

\`\`\`bash
# Run the full workflow
bash scripts/run.sh

# Or run individual steps
${workflow.steps.map(s => `${s.command}${s.args.length > 0 ? " " + s.args.join(" ") : ""}`).join("\n")}
\`\`\`

## Setup

\`\`\`bash
# Install all required tools
bash scripts/setup.sh
\`\`\`

## Triggers

${workflow.triggers.map(t => `- **${t}**`).join("\n")}

## Dependencies

${workflow.dependencies.map(d => `- ${d}`).join("\n")}
`;
}

// ── Script Generation ──────────────────────────────────────────────────

/**
 * Generate run.sh that chains CLI commands in order.
 */
export function generateRunScript(workflow: SkillWorkflow): string {
  const steps = workflow.steps.map(step => {
    const cmd = step.args.length > 0
      ? `${step.command} ${step.args.join(" ")}`
      : step.command;

    const conditionComment = step.condition ? `\n# Condition: ${step.condition}` : "";
    const failHandler = step.onFailure === "stop"
      ? ""  // set -e handles this
      : step.onFailure === "retry"
        ? ` || { echo "  Retrying ${step.name}..."; ${cmd}; }`
        : " || true";

    return `# Step: ${step.name} (${step.skill})${conditionComment}
echo "Running ${step.name}..."
${cmd}${failHandler}
echo "  ${step.name} complete."
`;
  }).join("\n");

  return `#!/usr/bin/env bash
set -euo pipefail

# ${workflow.name} — ${workflow.description}
# Generated by agents-cli workflow composer

echo "Starting ${workflow.name} workflow..."
echo ""

${steps}
echo ""
echo "${workflow.name} workflow complete."
`;
}

/**
 * Generate setup.sh that installs all tool dependencies.
 */
export function generateSetupScript(workflow: SkillWorkflow): string {
  // Deduplicate tool names from steps
  const tools = [...new Set(workflow.steps.map(s => s.skill.replace(/^src-/, "")))];

  return `#!/usr/bin/env bash
set -euo pipefail

# Setup script for ${workflow.name} workflow
# Generated by agents-cli workflow composer

echo "Installing dependencies for ${workflow.name}..."

# Verify tools are available
${tools.map(t => `command -v ${t} >/dev/null 2>&1 || { echo "Missing: ${t} — install it first"; exit 1; }`).join("\n")}

echo "All dependencies available."
`;
}

// ── Workflow Reference Doc ─────────────────────────────────────────────

/**
 * Generate workflow.md reference document with step diagram.
 */
export function generateWorkflowReference(workflow: SkillWorkflow): string {
  const diagram = workflow.steps.map((s, i) => {
    const arrow = i < workflow.steps.length - 1 ? " →" : "";
    return `[${s.name}]${arrow}`;
  }).join(" ");

  const stepTable = workflow.steps.map(s => {
    return `| ${s.name} | ${s.skill} | \`${s.command}\` | ${s.onFailure} | ${s.condition ?? "always"} |`;
  }).join("\n");

  return `# ${workflow.name} Workflow Reference

## Overview

${workflow.description}

## Pipeline Diagram

\`\`\`
${diagram}
\`\`\`

## Steps

| Step | Skill | Command | On Failure | Condition |
|------|-------|---------|------------|-----------|
${stepTable}

## Triggers

${workflow.triggers.map(t => `- **${t}**: ${getTriggerDescription(t)}`).join("\n")}
`;
}

function getTriggerDescription(trigger: string): string {
  const descriptions: Record<string, string> = {
    "manual": "Run on demand via CLI or command",
    "on-commit": "Run automatically on each commit (pre-commit hook)",
    "on-push": "Run automatically on push (CI/CD pipeline)",
    "schedule": "Run on a periodic schedule (cron)",
  };
  return descriptions[trigger] ?? "Custom trigger";
}

// ── Full Directory Generation ──────────────────────────────────────────

/**
 * Generate all files for a workflow skill directory.
 * Returns a map of relative paths to file contents.
 */
export function generateWorkflowSkillDirectory(
  workflow: SkillWorkflow,
): { skillMd: string; files: Record<string, string> } {
  return {
    skillMd: generateWorkflowSkillMd(workflow),
    files: {
      "scripts/run.sh": generateRunScript(workflow),
      "scripts/setup.sh": generateSetupScript(workflow),
      "references/workflow.md": generateWorkflowReference(workflow),
    },
  };
}
